### ISSUE TITLE
Mod Crashes on Mod Menu interaction

### ISSUE THREAD

**Issue by Divineaspect** [Immersive-Geology-Team/Immersive-Cooking#3]
**Describe the bug**
Mod Crashes on Mod Menu interaction

**To Reproduce**
1. Go to Mod Menu
2. Click on Immersive Cooking
3. See error

**Expected behavior**
Mod feature configs, etc

**Screenshots**

**Mods and their versions:**
Forge 36.2.0
immersivecooking-1.0.1
I'm not listing everything

**Additional context**
https://pastebin.com/yba0L9BW
https://paste.ee/p/AsKH3

**Comment by ddr3579** [comment]
this happens to me too

**Comment by NightmareTwilight** [comment]
I am unable to replicate this issue. Are you using a mod that changes the way the mod list functions?

**Comment by starryfae** [comment]
Using this mod https://www.curseforge.com/minecraft/mc-mods/config-menus-forge

Or this mod: https://www.curseforge.com/minecraft/mc-mods/configured

With Immersive Cooking

Consistenly causes the crash in 1.16.5
