### ISSUE TITLE
[Simple fix] cooking with Potato slices cooks for potato cubes

### ISSUE THREAD

**Issue by Shibva** [Immersive-Geology-Team/Immersive-Cooking#4]
**Describe the bug**
according to JEI the recipie for using Potato slices on the campfire will result in cooked potato cubes
**Screenshots**
![image](https://user-images.githubusercontent.com/38770780/139605511-a22dcca8-bf03-4b6b-9e42-347549aff8ca.png)

**Comment by Shibva** [comment]
using Crafttwealer I was able to correct the recipie for the time being

all I had todo was get the recpie for the cubes, remove it and copy the recpie that it was and replace a line
campfire.addRecipe("immersivecooking.fried_potato_cubes", <item:immersivecooking:fried_potato_cubes>, <item:immersivecooking:potato_cubes>, 0.35, 600);
campfire.removeByName("immersivecooking:fried_potato_cubes");

**Comment by NightmareTwilight** [comment]
Right, fixed. It'll be in the next version.
